api_platform:
    collection:
        pagination:
            client_items_per_page: true
            items_per_page: 10 # Default value
            items_per_page_parameter_name: itemsPerPage
    graphql:
        graphiql:
            enabled: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
